---
title: "Lab 2 - Boolean and Vector Space Model"
author: "Lý Hồng Phát"
date: "2023/02/14"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Code mẫu

Để thực hiện bài lab này bạn sẽ sử dụng phần code mẫu trong file **lab2.zip** và viết thêm các hàm hoặc các đoạn mã để thực hiện các công việc theo yêu cầu bên dưới.

## Cách nộp bài làm

Bạn sẽ nộp lại project đã làm (**không bao gồm các thư viện .jar** trong project). Ngoài ra, bạn cần nộp file báo cáo chứa java code và kết quả dùng file **Lab2.Rmd** được dung cấp sẵn. Đây là file **Rmarkdown**. **Markdown** là cú pháp đơn giản cho phép dễ dạng tạo các báo. **Rmarkdown** tích hợp code R với cú pháp **Markdown** để có thể tạo ra các báo cáo vừa có text, code và kết quả. Ở đây ta không dùng code R mà dùng Java. Xem thêm cú pháp của Rmarkdown ở <https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf> để biết cách viết. Dùng **RStudio** để soạn thảo và viết báo cáo. Khi cần biên dịch ra file .html thì nhấp vào **Knit** và chọn **Knit to HTML**. Nếu cần tìm hiểu thêm về **Rmarkdown** thì bạn có thể xem ở <https://bookdown.org/yihui/rmarkdown/>.

## Yêu cầu

### Lập chỉ mục bộ sưu tập tài liệu (document collection)

Đầu tiên, bạn cần thực thi file **LuceneBuildIndex.java** trong package **index** của project để lập chỉ mục bộ sưu tập tài liệu cho sẵn (file **example_corpus.gz** trong thư mục **docs** của project).

### 1. Hiện thực Boolean retrieval model với phép AND dùng chỉ mục đã tạo

Tiếp theo, bạn sẽ hiện thực hàm tìm kiếm Boolean AND dùng Lucene. Bạn sẽ phải duyệt qua posting list của từng từ (term) trong query từ index đã xây dựng được. Bạn cần hiện thực các hàm `searchBooleanAND` trong file **LuceneSearchIndex.java** để tìm tất cả tài liệu chứa tất cả các query term. Tập kết quả trả về cần được sắp xếp theo `docno`. Sau khi hiện thực hàm `searchBooleanAND` xong, bạn copy nội dung và dán đè vào đoạn mã bên dưới.

```{java}
/**
 * Hiện thực Boolean AND
 *
 * @param index		Lucene index reader
 * @param field 	index field để tìm query
 * @param queryTerms 	Danh sách các query term
 * 
 * @return 	Danh sách kết quả (sắp xếp theo docno)
 */
public static List<SearchResult> searchBooleanAND(IndexReader index, 
		   String field, List<String> queryTerms) throws Exception {
//  Viết phần hiện thực của bạn ở đây 
//  Bạn có thể viết thêm các hàm phụ trợ nếu cần thiết
//		SearchResult(int docid, String docno, double score)

	List<SearchResult> booleanSearchANDList = new ArrayList<SearchResult>();

//		Khởi tạo list answerDocID gồm các docId của term đầu tiên 
	List<Integer> answerDocId = new ArrayList<Integer>();

	PostingsEnum posting0 = MultiTerms.getTermPostingsEnum(index, field, new BytesRef(queryTerms.get(0)),
			PostingsEnum.FREQS);
	answerDocId.addAll(getListFromPostingList(posting0));

	for (int i = 0; i < queryTerms.size() - 1; i++) {
		PostingsEnum nextPosting = MultiTerms.getTermPostingsEnum(index, field, new BytesRef(queryTerms.get(i)),
				PostingsEnum.FREQS);
		answerDocId = andPostingList(answerDocId, getListFromPostingList(nextPosting));
	}

	for (int docId : answerDocId) {
//			Get docno
		String docnoString = LuceneUtils.getDocno(index, "docno", docId);
		booleanSearchANDList.add(new SearchResult(docId, docnoString, 1));
	}

//		sắp xếp theo docno
	for (int i = 0; i < booleanSearchANDList.size() - 1; i++) {
		for (int j = i + 1; j < booleanSearchANDList.size(); j++) {
			SearchResult firstDoc = booleanSearchANDList.get(i);
			SearchResult secDoc = booleanSearchANDList.get(j);

			int docno1 = Integer.valueOf(firstDoc.docno.substring(4));
			int docno2 = Integer.valueOf(secDoc.docno.substring(4));

			if (docno1 > docno2) {
				SearchResult temp = new SearchResult(booleanSearchANDList.get(i).docid,
						booleanSearchANDList.get(i).docno, booleanSearchANDList.get(i).score);
				booleanSearchANDList.get(i).docid = booleanSearchANDList.get(j).docid;
				booleanSearchANDList.get(i).docno = booleanSearchANDList.get(j).docno;
				booleanSearchANDList.get(i).score = booleanSearchANDList.get(j).score;
				booleanSearchANDList.get(j).docid = temp.docid;
				booleanSearchANDList.get(j).docno = temp.docno;
				booleanSearchANDList.get(j).score = temp.score;
			}
		}
	}

	return booleanSearchANDList;
}

public static List<Integer> andPostingList(List<Integer> p1, List<Integer> p2) {
	List<Integer> answer = new ArrayList<Integer>();

	int pp1 = 0;
	int pp2 = 0;

	while ((pp1 < p1.size()) && (pp2 < p2.size())) {
		if (p1.get(pp1) == p2.get(pp2)) {
			answer.add(p1.get(pp1));
			pp1++;
			pp2++;
		} else if (p1.get(pp1) < p2.get(pp2)) {
			answer.add(p1.get(pp1));
			pp1++;
		} else {
			answer.add(p2.get(pp2));
			pp2++;
		}
	}

	return answer;
}

public static List<Integer> getListFromPostingList(PostingsEnum postingsEnum) throws IOException {
	List<Integer> myList = new ArrayList<Integer>();
	int docId = postingsEnum.nextDoc();

	while (docId != DocIdSetIterator.NO_MORE_DOCS) {
		myList.add(docId);
		docId = postingsEnum.nextDoc();
	}
	return myList;
}
```

Kết quả sau khi chạy với input đã cho là (copy kết quả và dán vào đây, giữa cặp dấu `...`):

    0  0 ACM-133203   1  1.00000000 BooleanAND
    0  0 ACM-160689   2  1.00000000 BooleanAND
    0  0 ACM-160728   3  1.00000000 BooleanAND
    0  0 ACM-160761   4  1.00000000 BooleanAND
    0  0 ACM-383972   5  1.00000000 BooleanAND
    0  0 ACM-511717   6  1.00000000 BooleanAND
    0  0 ACM-511760   7  1.00000000 BooleanAND
    0  0 ACM-564408   8  1.00000000 BooleanAND
    0  0 ACM-636717   9  1.00000000 BooleanAND

### 2. Hiện thực các mô hình không gian vector (VSM) với hàm xếp hạng TF-IDF dùng chỉ mục đã tạo

Bạn sẽ hiện thực hàm xếp hạng TF-IDF dùng Lucene. Bạn sẽ phải duyệt qua posting list của từng từ (term) trong query từ index đã xây dựng được. Bạn cần hiện thực các hàm `searchTFIDF` trong file **LuceneSearchIndex.java**. Sau khi hiện thực hàm `searchTFIDF` xong, bạn copy nội dung và dán đè vào đoạn mã bên dưới. Hàm xếp hạng `TF-IDF` được mô tả bởi công thức sau: $$f(d,q) = \sum_{w \in q} freq(w, d) \times log \frac{N + 1}{n_w + 1}$$ Trong đó:

-   $f(d, q)$ là giá trị mô tả mức độ liên quan của tài liệu $d$ với truy vấn $q$,

-   $freq(w, d)$ là tần số của từ $w$ trong tài liệu $d$,

-   $n_w$ là số tài liệu chứa từ $w$ trong collection (còn gọi là *document frequency* của $w$ trong collection),

-   $N$ là số tài liệu trong collection.

```{java}
/**
 * Hiện thực TFxIDF dùng chiến lược term-at-a-time (taat)
 *
 * @param index 	Lucene index reader
 * @param field 	index field để tìm query
 * @param queryTerms 	Danh sách các query term
 *            
 * @return 	Danh sách kết quả (sắp xếp theo độ liên quan)
 */
public static List<SearchResult> searchTFIDF(IndexReader index, 
		String field, List<String> queryTerms) throws IOException {
	// Viết phần hiện thực của bạn ở đây
	// Bạn có thể viết thêm các hàm phụ trợ nếu cần thiết
	//		SearchResult(int docid, String docno, double score)

		List<SearchResult> searchTFIDF_List = new ArrayList<SearchResult>();

		int M = index.numDocs(); // số lượng documents

		for (String termString : queryTerms) {
			PostingsEnum posting = MultiTerms.getTermPostingsEnum(index, field, new BytesRef(termString),
					PostingsEnum.FREQS);
//			Lấy postingList của term

			Term term = new Term(field, termString);
			if (posting != null) {
//				if the term does not appear in any document, the posting object may be null
				int docid;

				while ((docid = posting.nextDoc()) != PostingsEnum.NO_MORE_DOCS) {
//					Lấy docno để lưu vào kết quả
					String docno = LuceneUtils.getDocno(index, "docno", docid);

//					Tính term frequency TF
					int freqWd = posting.freq();

//					Tính document frequency DF
					int DF = index.docFreq(term);

//					Tính IDF (Inverse document frequency)
					double IDF = Math.log((double) (M + 1) / (DF + 1));

//					Tính score của term này
					double score = freqWd * IDF;

					Boolean isExist = false;
					// Tìm trong kết quả xem đã tồn tại chưa
					for (SearchResult doc : searchTFIDF_List) {
						if (doc.docno.equals(docno)) {
							// Cộng dồn score nếu đã tồn tại trong kết quả
							doc.score += score;
							isExist = true;
							break;
						}
					}
					// Nếu chưa tồn tại thì thêm mới
					if (!isExist) {
						searchTFIDF_List.add(new SearchResult(docid, docno, score));
					}
				}
			}
		}

//		sắp xếp theo score
		for (int i = 0; i < searchTFIDF_List.size() - 1; i++) {
			for (int j = i + 1; j < searchTFIDF_List.size(); j++) {
				SearchResult firstDoc = searchTFIDF_List.get(i);
				SearchResult secDoc = searchTFIDF_List.get(j);
				if (firstDoc.score < secDoc.score) {
					SearchResult temp = new SearchResult(searchTFIDF_List.get(i).docid, searchTFIDF_List.get(i).docno,
							searchTFIDF_List.get(i).score);
					searchTFIDF_List.get(i).docid = searchTFIDF_List.get(j).docid;
					searchTFIDF_List.get(i).docno = searchTFIDF_List.get(j).docno;
					searchTFIDF_List.get(i).score = searchTFIDF_List.get(j).score;
					searchTFIDF_List.get(j).docid = temp.docid;
					searchTFIDF_List.get(j).docno = temp.docno;
					searchTFIDF_List.get(j).score = temp.score;
				}
			}
		}

		return searchTFIDF_List;
}
```

Kết quả sau khi chạy với input đã cho là (copy kết quả và dán vào đây, giữa cặp dấu `...`):

    0  0 ACM-1148204  1  9.68601321 TFIDF
    0  0 ACM-564408   2  9.08984702 TFIDF
    0  0 ACM-2009998  3  8.24864674 TFIDF
    0  0 ACM-383972   4  8.24864674 TFIDF
    0  0 ACM-1277796  5  8.16696871 TFIDF
    0  0 ACM-1390416  6  8.08529068 TFIDF
    0  0 ACM-1835650  7  7.92193462 TFIDF
    0  0 ACM-860437   8  7.84025659 TFIDF
    0  0 ACM-2609503  9  7.16241237 TFIDF

### 3. Hiện thực các mô hình không gian vector (VSM) với hàm xếp hạng cosine dùng chỉ mục đã tạo

Bạn sẽ hiện thực hàm xếp hạng cosine dùng Lucene. Bạn sẽ phải duyệt qua posting list của từng từ (term) trong query từ index đã xây dựng được. Bạn cần hiện thực các hàm `searchSVMCosine` trong file **LuceneSearchIndex.java**. Sau khi hiện thực hàm `searchSVMCosine` xong, bạn copy nội dung và dán đè vào đoạn mã bên dưới. Hàm xếp hạng `SVM Cosine` được mô tả bởi công thức sau:

$$f(d,q) = \frac{\sum_{w \in q} freq(w, q) \times freq(w, d)}{\sqrt{\sum_{w \in q} freq(w, q)^2} \times \sqrt{\sum_{w \in d} freq(w, d)^2}} $$

Trong đó:

-   $f(d, q)$ là giá trị mô tả mức độ liên quan của tài liệu $d$ với truy vấn $q$,

-   $freq(w, q)$, $freq(w, d)$ lần lượt là tần số của từ $w$ trong truy vấn $q$ và tài liệu $d$.

```{java}
/**
 * Hiện thực VSM (cosine similarity) dùng chiến lược term-at-a-time (taat)
 *
 * @param index 	Lucene index reader
 * @param field 	index field để tìm query
 * @param queryTerms 	Danh sách các query term
 *            
 * @return 	Danh sách kết quả (sắp xếp theo độ liên quan)
 */
public static List<SearchResult> searchSVMCosine(IndexReader index, 
		String field, List<String> queryTerms) throws IOException {
	// Viết phần hiện thực của bạn ở đây
	// Bạn có thể viết thêm các hàm phụ trợ nếu cần thiết
	
  List<SearchResult> searchVSMCosineList = new ArrayList<SearchResult>();

//		sumFreqWq bình phương: bình phương tổng tần số của từ w trong truy vấn q
	List<Integer> qfList = new ArrayList<Integer>();
	double SumFreqWq_2 = 0;
	for (int i = 0; i < queryTerms.size(); i++) {
		String term = queryTerms.get(i);
		qfList.add(freqWinQ(term, queryTerms));
		SumFreqWq_2 += qfList.get(i) * qfList.get(i);
	}
	List<Integer> tfList = new ArrayList<Integer>();

	for (int i = 0; i < queryTerms.size(); i++) {
		String termString = queryTerms.get(i);
		
//			Lấy postingList của term
		PostingsEnum posting = MultiTerms.getTermPostingsEnum(index, field, new BytesRef(termString),
				PostingsEnum.FREQS);

//			Term term = new Term(field, termString);
		if (posting != null) {
			int docid;

			while ((docid = posting.nextDoc()) != PostingsEnum.NO_MORE_DOCS) {
//					Lấy docno để lưu vào kết quả
				String docno = LuceneUtils.getDocno(index, "docno", docid);

//					Tính term frequency TF
				int freqWd = posting.freq();
				tfList.add(freqWd);

//					Tính tần số của từ w trong truy vấn q
				double fredWq = qfList.get(i);

//					Tính score của term này
				double score = (fredWq * freqWd);

				Boolean isExist = false;
				// Tìm trong kết quả xem đã tồn tại chưa
				for (SearchResult doc : searchVSMCosineList) {
					if (doc.docno.equals(docno)) {
						// Cộng dồn score nếu đã tồn tại trong kết quả
						doc.score += score;
						isExist = true;
						break;
					}
				}
				// Nếu chưa tồn tại thì thêm mới
				if (!isExist) {
					searchVSMCosineList.add(new SearchResult(docid, docno, score));
				}
			}
		}
	}
	
//		sumTF_2: tổng TF bình phương
	double sumTF_2 = 0;
	for (int tf : tfList) {
		sumTF_2 += tf * tf;
	}
	
	for (SearchResult score : searchVSMCosineList) {
		double newScore = score.getScore() / (Math.sqrt(SumFreqWq_2) * Math.sqrt(sumTF_2));
		score.setScore(newScore);
	}

//		sắp xếp theo score
	for (int i = 0; i < searchVSMCosineList.size() - 1; i++) {
		for (int j = i + 1; j < searchVSMCosineList.size(); j++) {
			SearchResult firstDoc = searchVSMCosineList.get(i);
			SearchResult secDoc = searchVSMCosineList.get(j);
			if (firstDoc.score < secDoc.score) {
				SearchResult temp = new SearchResult(searchVSMCosineList.get(i).docid,
						searchVSMCosineList.get(i).docno, searchVSMCosineList.get(i).score);
				searchVSMCosineList.get(i).docid = searchVSMCosineList.get(j).docid;
				searchVSMCosineList.get(i).docno = searchVSMCosineList.get(j).docno;
				searchVSMCosineList.get(i).score = searchVSMCosineList.get(j).score;
				searchVSMCosineList.get(j).docid = temp.docid;
				searchVSMCosineList.get(j).docno = temp.docno;
				searchVSMCosineList.get(j).score = temp.score;
			}
		}
	}

	return searchVSMCosineList;
}

public static int freqWinQ(String word, List<String> querry) {
	int freqWq = 0;
	for (String t : querry) {
		if (t.equals(word)) {
			freqWq = freqWq + 1;
		}
	}
	return freqWq;
}
```

Kết quả sau khi chạy với input đã cho là (copy kết quả và dán vào đây, giữa cặp dấu `...`):

    0  0 ACM-1148204  1  0.25607376 VSMCosine
    0  0 ACM-564408   2  0.23473428 VSMCosine
    0  0 ACM-1390416  3  0.21339480 VSMCosine
    0  0 ACM-1277796  4  0.21339480 VSMCosine
    0  0 ACM-2009998  5  0.21339480 VSMCosine
    0  0 ACM-860437   6  0.21339480 VSMCosine
    0  0 ACM-1835650  7  0.21339480 VSMCosine
    0  0 ACM-383972   8  0.21339480 VSMCosine
    0  0 ACM-1009026  9  0.19205532 VSMCosine
